// <auto-generated />
namespace BiteCardEntityModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addMoreSeedData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMoreSeedData));
        
        string IMigrationMetadata.Id
        {
            get { return "201302020638358_addMoreSeedData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
