// <auto-generated />
namespace BiteCardEntityModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class firstMigrationforTheBiteCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstMigrationforTheBiteCard));
        
        string IMigrationMetadata.Id
        {
            get { return "201302020417506_firstMigrationforTheBiteCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
