// <auto-generated />
namespace BiteCardEntityModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addSeedDataToAllTablesChangePriceToDouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSeedDataToAllTablesChangePriceToDouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201302020629305_addSeedDataToAllTablesChangePriceToDouble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
