// <auto-generated />
namespace BiteCardEntityModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedOrderContext_MessageTable2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedOrderContext_MessageTable2));
        
        string IMigrationMetadata.Id
        {
            get { return "201302020435147_addedOrderContext_MessageTable2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
