// <auto-generated />
namespace BiteCardEntityModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeOrderFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeOrderFK));
        
        string IMigrationMetadata.Id
        {
            get { return "201302030425093_removeOrderFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
