// <auto-generated />
namespace BiteCards.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class test_effect_remove_listItemsFromCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_effect_remove_listItemsFromCard));
        
        string IMigrationMetadata.Id
        {
            get { return "201302010501213_test_effect_remove_listItemsFromCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
