// <auto-generated />
namespace BiteCards.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addFKToImagesTable_RemoveExtraFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFKToImagesTable_RemoveExtraFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201302010508382_addFKToImagesTable_RemoveExtraFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
